version: '3'
services:
  app:
    build: .
    command:
     #"uvicorn app:app --host 0.0.0.0 --port 80 --reload"
     - uvicorn
     - app:app
     - --host=0.0.0.0
     -  --port=80
     - --reload
    volumes:
      - .:/app
    ports:
      - 8089:80
    #environment:
    # VRS_API_ONLY: true
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
