version: '3'
services:
  app:
    build: .
    command:
     - uvicorn
     - src.adsb_api.app:app
     - --host=0.0.0.0
     -  --port=80
     - --reload
    volumes:
      - .:/app
    environment:
      - INSECURE=1
      - ADSBLOL_ENABLED_BG_TASKS=
    ports:
      - 8089:80
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
